'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.0.0/24")>  _
        Public Property IPRange() As String
            Get
                Return CType(Me("IPRange"),String)
            End Get
            Set
                Me("IPRange") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("E:\KLT\LedShow\KKLT Led Show v2\KLT LedShow\Database")>  _
        Public Property DatabaseFolder() As String
            Get
                Return CType(Me("DatabaseFolder"),String)
            End Get
            Set
                Me("DatabaseFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Screen 1")>  _
        Public Property MonitorControl() As String
            Get
                Return CType(Me("MonitorControl"),String)
            End Get
            Set
                Me("MonitorControl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Screen 2")>  _
        Public Property MonitorPrimary() As String
            Get
                Return CType(Me("MonitorPrimary"),String)
            End Get
            Set
                Me("MonitorPrimary") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Screen 3")>  _
        Public Property MonitorSecond() As String
            Get
                Return CType(Me("MonitorSecond"),String)
            End Get
            Set
                Me("MonitorSecond") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Titanic")>  _
        Public Property ProjectName() As String
            Get
                Return CType(Me("ProjectName"),String)
            End Get
            Set
                Me("ProjectName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Locked() As Boolean
            Get
                Return CType(Me("Locked"),Boolean)
            End Get
            Set
                Me("Locked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("E:\KLT\LedShow\KKLT Led Show v2\ColorMaps")>  _
        Public Property PaletteImagesPath() As String
            Get
                Return CType(Me("PaletteImagesPath"),String)
            End Get
            Set
                Me("PaletteImagesPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("E:\KLT\LedShow\KKLT Led Show v2\Effects")>  _
        Public Property EffectsImagePath() As String
            Get
                Return CType(Me("EffectsImagePath"),String)
            End Get
            Set
                Me("EffectsImagePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4048")>  _
        Public Property DDPPort() As String
            Get
                Return CType(Me("DDPPort"),String)
            End Get
            Set
                Me("DDPPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property LedsPerMeter() As String
            Get
                Return CType(Me("LedsPerMeter"),String)
            End Get
            Set
                Me("LedsPerMeter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property PodiumBreedte() As String
            Get
                Return CType(Me("PodiumBreedte"),String)
            End Get
            Set
                Me("PodiumBreedte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("400")>  _
        Public Property PodiumHoogte() As String
            Get
                Return CType(Me("PodiumHoogte"),String)
            End Get
            Set
                Me("PodiumHoogte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CustomEffectC1() As String
            Get
                Return CType(Me("CustomEffectC1"),String)
            End Get
            Set
                Me("CustomEffectC1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CustomEffectC2() As String
            Get
                Return CType(Me("CustomEffectC2"),String)
            End Get
            Set
                Me("CustomEffectC2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CustomEffectC3() As String
            Get
                Return CType(Me("CustomEffectC3"),String)
            End Get
            Set
                Me("CustomEffectC3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CustomEffectC4() As String
            Get
                Return CType(Me("CustomEffectC4"),String)
            End Get
            Set
                Me("CustomEffectC4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CustomEffectC5() As String
            Get
                Return CType(Me("CustomEffectC5"),String)
            End Get
            Set
                Me("CustomEffectC5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property CustomEffectIntensity() As String
            Get
                Return CType(Me("CustomEffectIntensity"),String)
            End Get
            Set
                Me("CustomEffectIntensity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property CustomEffectSpeed() As String
            Get
                Return CType(Me("CustomEffectSpeed"),String)
            End Get
            Set
                Me("CustomEffectSpeed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property CustomEffectBrightness() As String
            Get
                Return CType(Me("CustomEffectBrightness"),String)
            End Get
            Set
                Me("CustomEffectBrightness") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UP")>  _
        Public Property CustomEffectDirection() As String
            Get
                Return CType(Me("CustomEffectDirection"),String)
            End Get
            Set
                Me("CustomEffectDirection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CustomEffectPosition() As String
            Get
                Return CType(Me("CustomEffectPosition"),String)
            End Get
            Set
                Me("CustomEffectPosition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property CustomEffectDuration() As String
            Get
                Return CType(Me("CustomEffectDuration"),String)
            End Get
            Set
                Me("CustomEffectDuration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property CustomEffectBrightnessEffect() As String
            Get
                Return CType(Me("CustomEffectBrightnessEffect"),String)
            End Get
            Set
                Me("CustomEffectBrightnessEffect") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property CustomEffectDispersion() As String
            Get
                Return CType(Me("CustomEffectDispersion"),String)
            End Get
            Set
                Me("CustomEffectDispersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ScriptPDF() As String
            Get
                Return CType(Me("ScriptPDF"),String)
            End Get
            Set
                Me("ScriptPDF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("800")>  _
        Public Property SplitPosition() As Integer
            Get
                Return CType(Me("SplitPosition"),Integer)
            End Get
            Set
                Me("SplitPosition") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.KLT_LedShow.My.MySettings
            Get
                Return Global.KLT_LedShow.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
